### PR TITLE
add feature of measuring extendability.

### PR DESCRIPTION
**Pull request by fatemehkarimi**

### CODE REVIEW

**Review by m-zakeri — CHANGES_REQUESTED** [review]
1- Follow PEP instructions for naming python entities, specifically module names:
https://www.python.org/dev/peps/pep-0008/ 

2- Merge main.py to `extendibility,py` for better consistency

3- Ensure fixing issues discussed in presentation session

**Comment by m-zakeri** [comment]
ToDo:
1- Follow PEP instructions for naming python entities, specifically module names:
https://www.python.org/dev/peps/pep-0008/
2- Merge `main.py` to `extendibility.py` for better consistency
@fatemehkarimi @niloofarizadyar

**Comment by fatemehkarimi** [comment]
@m-zakeri 
I know that camelCase should not be used according to PEP 8, but ANTLR uses camelCase naming convention, and I did so to be consistent with it. do you accept this explanation or I should change the names?

**Comment by m-zakeri** [comment]
> @m-zakeri I know that camelCase should not be used according to PEP 8, but ANTLR uses camelCase naming convention, and I did so to be consistent with it. do you accept this explanation or I should change the names?

I think we should not repeat others' mistakes. 
Also, please address my second commnet.

**Comment by fatemehkarimi** [comment]
@m-zakeri  The branch is ready.
please merge

**Pull request merged**
